### ISSUE TITLE
Homebrew Formula

### ISSUE THREAD

**Issue by soffes** [gbdk-2020/gbdk-2020#131]
It would be great if GBDK had a [Homebrew](https://brew.sh) formula to make it easier to install the tools on macOS.

Thanks so much for your work on this project!

**Comment by basxto** [comment]
You could take a look at my [AUR script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gbdk-2020), but I use some not yet merged changes (`BINDIR` part). And depend on SDCC instead of including it, dunno how that's handled in homebrew.

**Comment by basxto** [comment]
4.0.3 has those changes merged in

**Comment by bbbbbr** [comment]
> It would be great if GBDK had a [Homebrew](https://brew.sh) formula to make it easier to install the tools on macOS.
> 
> Thanks so much for your work on this project!

What are the preferred steps currently taken to install it on macOS?
