### ISSUE TITLE
Why use custom data types (UINT16, etc)?

### ISSUE THREAD

**Issue by spth** [gbdk-2020/gbdk-2020#162]
Why does gbdk use data types like UINT16, DWORD, etc?

As far as I can see, they are just equivalent to standard C types from stdint.h, so why not just use the latter?

Also, gbdk uses signed char as BOOLEAN. From the name I guess that type is meant to just represent boolean values, so bool from stdbool.h should be a more efficient choice.

**Comment by untoxa** [comment]
Hello Philipp,

Friday, March 26, 2021, 11:59:24 AM, you wrote:

PKK> Why does gbdk use data types like UINT16, DWORD, etc?

PKK> As far as I can see, they are just equivalent to standard C types from stdint.h, so why not just use the latter?

PKK> Also, gbdk uses signed char as BOOLEAN. From the name I guess that type is meant to just represent boolean values, so bool from stdbool.h should be a more efficient choice.

that's legacy of the old GBDK design. i agree, that is a bad practice.


-- 
Best regards,
 Tony                            ***@***.***

**Comment by bbbbbr** [comment]
Replaced `UBYTE`/`UINT8`/etc with stdint types for examples and gbdk libs where appropriate.

Does not include changes for `BOOLEAN`

**Comment by untoxa** [comment]
i think we can close this now, due to: https://github.com/gbdk-2020/gbdk-2020/pull/195 and https://github.com/gbdk-2020/gbdk-2020/pull/196
