### ISSUE TITLE
move_metasprite()  CGB compatibility

### ISSUE THREAD

**Issue by bbbbbr** [gbdk-2020/gbdk-2020#172]
Since move_metasprite() writes the sprite properties byte that means it will reset any CGB palette assignment (or BG/WIN prioity, etc).

* Docs should be updated to note this

* Do we want to allow either masking the write to sprite props to preserve other flags, and/or allowing a default a props value as an argument to the png2mtspr conversion tool?

Since metasprite frames may use varying amounts of sprites, it may not be good to rely on them using the same index or number of sprites or existing property values.

**Comment by untoxa** [comment]
the idea is to dynamically render whole OAM. different animation frames of a metasprite might require different amount of hardware sprites, that's why attributes can't be merged with OAM: very likely it contains garbage. you can put metsaprite structures into RAM and modify them if you want to manipulate attributes at runtime.

**Comment by bbbbbr** [comment]
Yeah, I just edited my comment with the same thought about varying amounts. :)
Maybe there could be some facility for setting flags in most efficient way, since it may become a common operation.

**Comment by untoxa** [comment]
the most efficient way is to keep metasprite descriptors in RAM for that. you can do whatever you want then.

**Comment by untoxa** [comment]
I'm closing this issue, because there is no actual bug or problem described,

**Comment by bbbbbr** [comment]
Re-opening the issue because, at the least, there needs to be documentation of the limitations when working with png2mtspr so that a couple things are clear to users:

* Generally give warning about use with CGB
* Specifically note that it overwrites sprite property flags and describe suggested workarounds
* Explain process for how colors get interpreted so that it is clear how to get the expected results, and what should not be done in order to avoid unexpected results (such as using colors colors that are close shades to each-other, which will then get merged).
* Possibly implement default sprite properties value as input parameter to png2mtspr

Assigned to myself, at least for docs part.

**Comment by untoxa** [comment]
read the issue title and your own original problem description, @bbbbbr. :)
