### ISSUE TITLE
/opt/gbdkbin/sdcc: No such file or directory error when compiling main.c in Linux

### ISSUE THREAD

**Issue by Liamx220** [gbdk-2020/gbdk-2020#175]
OS: Pop OS 64bit GNU/Linux

When I try to compile my main.c file it throws up this error:
/opt/gbdk/bin/lcc: /opt/gbdkbin/sdcc: No such file or directory

I'm know very little about this stuff but I think there needs to be a / between gbdkbin.
Thanks for any help in advance.

**Comment by untoxa** [comment]
Do examples in gbdk-2020/examples/gb compile?

**Comment by Liamx220** [comment]
Yes they do.

**Comment by untoxa** [comment]
Follow the examples.
