### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by WilliamWangPeng** [gbdk-2020/gbdk-2020#187]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119220892-3c996c00-bb1f-11eb-9ad8-1dc5183aa22f.png)

thank you  
best regards to you  
William

**Comment by bbbbbr** [comment]
SDCC is the compiler used by GBDK.

Per the build instructions, you must:
* Create SDCCDIR environment variable, that points into the folder, where you installed sdcc

So for example, on Linux: `export SDCCDIR=/path/to/your/sdcc`

Then try building and it should be able to copy the sdcc binaries to the build dir.

https://github.com/gbdk-2020/gbdk-2020#build-instructions
