### ISSUE TITLE
can't compile GB ROMs on raspberry pi 3 b+ (raspbian buster)

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [gbdk-2020/gbdk-2020#190]
when i run my make.sh script through the terminal this is what it says:
```
pi@raspberry-pi:~/gbdk-linux/game $ bash make.sh
/home/pi/gbdk-linux/bin/lcc: -o /home/pi/gbdk-linux/game/main.o ignored
'home/pi/gbdk-linux/bin/lcc: can't find `/home/pi/gbdk-linux/game/main.c
'home/pi/gbdk-linux/bin/lcc: can't find `/home/pi/gbdk-linux/game/main.o
```

this is whats in my script:
```
~/gbdk-linux/bin/lcc -Wa-l -Wl-m -Wl-j -DUSE_SFR_FOR_REG -c -o /home/pi/gbdk-linux/game/main.o /home/pi/gbdk-linux/game/main.c
~/gbdk-linux/bin/lcc -Wa-l -Wl-m -Wl-j-DUSE_SFR_FOR_REG -o /home/pi/gbdk-linux/game/main.gb /home/pi/gbdk-linux/game/main.o
```

if I ls the folder where the files it says it can't find are this is what it says:
pi@raspberry-pi:~/gbdk-linux/game $ ls
```
bg.c                   main.asm  main.ihx  main.noi  make.sh  sprites.c
Checksum_calculator.c  main.c    main.lst  main.o    music.c
drm.c                  main.gb   main.map  main.sym  sound.c
```
the make.sh script is the same that i use on windows 7 and it works fine there the only thing I changed when i copied it to my raspberry pi is the file paths because the pi couldn't find lcc or my project files, how do I fix this so i can compile and test my game on raspbian without creating a makefile? 

I built gbdk for the pi by following the instructions here: https://gbdev.gg8.se/forums/viewtopic.php?id=770 at reply number 4 because the precompiled version for linux is for x86 and the pi 3 b+ is arm so I was getting errors when it would try to run lcc

(edit to add code tags)

**Comment by bbbbbr** [comment]
Which version of GBDK-2020 do you use/build from?
Did you test to see if the included examples build ok?

**Comment by meeeeeeeeeeeeeeee** [comment]
I'm using GBDK 4.0.3 and sdcc is the latest version for arm that I got yesterday from here: http://sourceforge.net/projects/sdcc/files/snapshot_builds/armv6l-unknown-linux-gnueabihf/sdcc-snapshot-armv6l-unknown-linux-gnueabihf-20210121-12016.tar.bz2/download

**Comment by bbbbbr** [comment]
At least for the example project, there seems to be some incompatibility with sdasgb it's using.

For that example project (`sgb_border`), can you change the line in the Makefile as below. It should give more detailed output about how sdasgb is being called.

From this:
`$(CC) -Wm-ys -o border.gb border.c sgb_border.c border_data.c`

To this: (add `-v` for verbose lcc output)
`$(CC) -Wm-ys -v -o border.gb border.c sgb_border.c border_data.c`

Then try to build it again.

Also, just to be sure, lets double check the sdcc version number (in your `gbdk/bin/`)
`./sdcc -v`

**Comment by meeeeeeeeeeeeeeee** [comment]
This is what i get after changing the makefile in the sgb_border folder:

pi@raspberry-pi:~/gbdk-linux/examples/gb $ make
make -C sgb_border/. 
make[1]: Entering directory '/home/pi/gbdk-linux/examples/gb/sgb_border'
../../../bin/lcc -Wm-ys -v -o border.gb border.c sgb_border.c border_data.c
../../../bin/lcc $Id: lcc.c,v 2.0 2021/05/29 00:47:33 gbdk-2020 Exp $
border.c:
"../../../"bin/sdcc -mgbz80 --no-std-crt0 --fsigned-char --use-stdout -Wa-pogn -DGB=1 -DGAMEBOY=1 -DINT_16_BITS -D__LCC__ -I"../../../"include -c border.c -o /tmp/lcc35150.o

sdas Assembler V02.00 + NoICE + SDCC mods  (GameBoy Z80-like CPU)


Copyright (C) 2012  Alan R. Baldwin
This program comes with ABSOLUTELY NO WARRANTY.

Usage: [-Options] file
Usage: [-Options] outfile file1 [file2 file3 ...]
  -d   Decimal listing
  -q   Octal   listing
  -x   Hex     listing (default)
  -g   Undefined symbols made global
  -a   All user symbols made global
  -b   Display .define substitutions in listing
  -bb  and display without .define substitutions
  -c   Disable instruction cycle count in listing
  -j   Enable NoICE Debug Symbols
  -y   Enable SDCC  Debug Symbols
  -l   Create list   file/outfile[.lst]
  -o   Create object file/outfile[.rel]
  -s   Create symbol file/outfile[.sym]
  -p   Disable automatic listing pagination
  -u   Disable .list/.nlist processing
  -w   Wide listing format for symbol table
  -z   Disable case sensitivity for symbols
  -f   Flag relocatable references by  `   in listing file
  -ff  Flag relocatable references by mode in listing file
  -I   Add the named directory to the include file
       search path.  This option may be used more than once.
       Directories are searched in the order given.

removing 
sgb_border.c:
../../../bin/sdcc -mgbz80 --no-std-crt0 --fsigned-char --use-stdout -Wa-pogn -DGB=1 -DGAMEBOY=1 -DINT_16_BITS -D__LCC__ -I../../../include -c sgb_border.c -o /tmp/lcc35151.o

sdas Assembler V02.00 + NoICE + SDCC mods  (GameBoy Z80-like CPU)


Copyright (C) 2012  Alan R. Baldwin
This program comes with ABSOLUTELY NO WARRANTY.

Usage: [-Options] file
Usage: [-Options] outfile file1 [file2 file3 ...]
  -d   Decimal listing
  -q   Octal   listing
  -x   Hex     listing (default)
  -g   Undefined symbols made global
  -a   All user symbols made global
  -b   Display .define substitutions in listing
  -bb  and display without .define substitutions
  -c   Disable instruction cycle count in listing
  -j   Enable NoICE Debug Symbols
  -y   Enable SDCC  Debug Symbols
  -l   Create list   file/outfile[.lst]
  -o   Create object file/outfile[.rel]
  -s   Create symbol file/outfile[.sym]
  -p   Disable automatic listing pagination
  -u   Disable .list/.nlist processing
  -w   Wide listing format for symbol table
  -z   Disable case sensitivity for symbols
  -f   Flag relocatable references by  `   in listing file
  -ff  Flag relocatable references by mode in listing file
  -I   Add the named directory to the include file
       search path.  This option may be used more than once.
       Directories are searched in the order given.

removing 
border_data.c:
../../../bin/sdcc -mgbz80 --no-std-crt0 --fsigned-char --use-stdout -Wa-pogn -DGB=1 -DGAMEBOY=1 -DINT_16_BITS -D__LCC__ -I../../../include -c border_data.c -o /tmp/lcc35152.o

sdas Assembler V02.00 + NoICE + SDCC mods  (GameBoy Z80-like CPU)


Copyright (C) 2012  Alan R. Baldwin
This program comes with ABSOLUTELY NO WARRANTY.

Usage: [-Options] file
Usage: [-Options] outfile file1 [file2 file3 ...]
  -d   Decimal listing
  -q   Octal   listing
  -x   Hex     listing (default)
  -g   Undefined symbols made global
  -a   All user symbols made global
  -b   Display .define substitutions in listing
  -bb  and display without .define substitutions
  -c   Disable instruction cycle count in listing
  -j   Enable NoICE Debug Symbols
  -y   Enable SDCC  Debug Symbols
  -l   Create list   file/outfile[.lst]
  -o   Create object file/outfile[.rel]
  -s   Create symbol file/outfile[.sym]
  -p   Disable automatic listing pagination
  -u   Disable .list/.nlist processing
  -w   Wide listing format for symbol table
  -z   Disable case sensitivity for symbols
  -f   Flag relocatable references by  `   in listing file
  -ff  Flag relocatable references by mode in listing file
  -I   Add the named directory to the include file
       search path.  This option may be used more than once.
       Directories are searched in the order given.

removing 
rm /tmp/lcc35152.adb /tmp/lcc35150.o /tmp/lcc35150.asm /tmp/lcc35150.lst /tmp/lcc35150.sym /tmp/lcc35150.adb /tmp/lcc35151.o /tmp/lcc35151.asm /tmp/lcc35151.lst /tmp/lcc35151.sym /tmp/lcc35151.adb /tmp/lcc35152.o /tmp/lcc35152.asm /tmp/lcc35152.lst /tmp/lcc35152.sym
make[1]: *** [Makefile:4: all] Error 1
make[1]: Leaving directory '/home/pi/gbdk-linux/examples/gb/sgb_border'
make: *** [Makefile:14: sgb_border/.] Error 2

and this is the version of sdcc i have:

pi@raspberry-pi:~/gbdk-linux/bin $ ./sdcc -v
SDCC : mcs51/z80/z180/r2k/r2ka/r3ka/gbz80/tlcs90/ez80_z80/z80n/ds390/TININative/hc08/s08/stm8/pdk13/pdk14/pdk15 4.0.7 #12016 (Linux)
published under GNU General Public License (GPL)

and this is my environment settings and linux version:

pi@raspberry-pi:~ $ printenv
SHELL=/bin/bash
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_MENU_PREFIX=lxde-pi-
LANGUAGE=en_US.UTF-8
_LXSESSION_PID=500
SSH_AUTH_SOCK=/tmp/ssh-kpiiSmlZeej1/agent.500
XDG_CONFIG_HOME=/home/pi/.config
DESKTOP_SESSION=LXDE-pi
SSH_AGENT_PID=533
NO_AT_BRIDGE=1
XDG_SEAT=seat0
PWD=/home/pi
XDG_SESSION_DESKTOP=lightdm-xsession
LOGNAME=pi
QT_QPA_PLATFORMTHEME=qt5ct
XDG_SESSION_TYPE=x11
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
XAUTHORITY=/home/pi/.Xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm/data/pi
HOME=/home/pi
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=LXDE
VTE_VERSION=5402
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
TERM=xterm-256color
USER=pi
DISPLAY=:0.0
SHLVL=1
XDG_VTNR=7
XDG_SESSION_ID=c1
XDG_RUNTIME_DIR=/run/user/1000
LC_ALL=en_US.UTF-8
XDG_DATA_DIRS=/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
GDMSESSION=lightdm-xsession
SAL_USE_VCLPLUGIN=gtk3
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
TEXTDOMAIN=Linux-PAM
_=/usr/bin/printenv
pi@raspberry-pi:~ $ uname -a
Linux raspberry-pi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

**Comment by untoxa** [comment]
Raspberry pi SDCC snapshot is very old and won’t work with the latest GBDK-2020 from the develop branch. You should compile SDCC from the trunk yourself as discussed here: https://gbdev.gg8.se/forums/viewtopic.php?id=792 it compiles fine.

**Comment by untoxa** [comment]
Or, alternatively, you can try GBDK-2020 from the master branch. Probably it will work.

**Comment by meeeeeeeeeeeeeeee** [comment]
I tried using the Master version of GBDK (compiled from source again), I got no errors when it was compiling but it still can't find my main.c and main.o files, I tried compiling the latest version of SDCC from source (over 12 times) and installed it but it still doesn't work, I unzipped the archive the sdcc source code came in to ,my home folder with xarchiver, opened lxterminal, went to the sdcc folder in my home folder, ran configure then make (with the swapfile it kept crashing because the pi 3 b+ doesn't have enough RAM so i made a swap partition with gparted and edited my fstab file to have the swap partition mount at boot) rebooted, ran make again and I still get errors, but when i checked in /home/pi/sdcc/bin there is a file inside called sdcc and if i use the file command on it i get:

pi@raspberry-pi:~/sdcc/bin $ file sdcc
sdcc: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=88a89a4ceaa60b7daff74d22d7abacb8d3a78f1e, with debug_info, not stripped

I copied that to /usr/local/bin using: sudo cp sdcc /usr/local/bin

then when I go in /usr/local/bin and use the file command on sdcc again i get:
 pi@raspberry-pi:/usr/local/bin $ file sdcc
sdcc: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=88a89a4ceaa60b7daff74d22d7abacb8d3a78f1e, with debug_info, not stripped

and the version is:
pi@raspberry-pi:~/sdcc/bin $ sdcc -v
SDCC : mcs51/z80/z180/r2k/r2ka/r3ka/gbz80/tlcs90/ez80_z80/z80n/ds390/pic16/pic14/TININative/ds400/hc08/s08/stm8/pdk13/pdk14/pdk15 4.1.6 #12407 (Linux)
published under GNU General Public License (GPL)

there could still be a problem with sdcc but I can't get it to compile right for armv6 so until someone else builds it correctly on a pi 4 or a PC I won't know (I tried building sdcc on my desktop in debian 10.9 LXDE and linux mint 19.1 MATE but could not get the container I built to cross compile programs for the pi to work) 

but the problem could also be lcc or something on the pi 3 b+

**Comment by untoxa** [comment]
probably you should ask questions about SDCC here: https://sourceforge.net/p/sdcc/

i compiled that a month ago:
https://www.dropbox.com/s/uooxdarcy0s7yt7/gbdk-2020-4.0.4b1.raspberry.tar.gz?dl=1

**Comment by meeeeeeeeeeeeeeee** [comment]
I have fixed the first problem I was having with the "file not found" error by moving my project folder to my home folder and creating a Makefile inside then deleting the old files and compiling GBDK again the same way I did it the first time but with the source code from the master branch and properly installing it to /opt right after make finished running, my game builds now on the raspberry pi but I don't know where it's building to,

this is my Makefile:

`BIN=/opt/gbdk/bin
OBJ=~/game
GAME=main

$(GAME).o: $(OBJ)/$(GAME).c
	$(BIN)/lcc -Wa-l -Wl-m -Wl-j -c -o $(OBJ)/$(GAME).o $(OBJ)/$(GAME).c

$(GAME).gb: $(OBJ)/$(GAME).o
	$(BIN)/lcc -Wa-l -Wl-m -Wl-j -o $(OBJ)/$(GAME).gb $(OBJ)/$(GAME).o

#.PHONY = play
#play: $(GAME).gb
#	bgb $(GAME).gb

#.PHONY = clean
#clean:
#	rm -rf $(OBJ)
#	rm -f $(GAME).gb
`
which is a modified version of https://github.com/Zal0/GBSoundDemo/blob/master/Makefile

now when I go to my project folder and run make it looks like it's working and finishes whatever it had to do but then if i check the folder where ROM is suposed to be it is not there, I tried to run 
`sudo find / -name "main.gb"`

but it fails with an error:

find: '/run/user/1000/gvfs': Permission denied

If i exlude that folder by running: 

sudo find / -iname main.gb ! -path /run/user/1000/gvfs/*

it also fails with a "permission denied" error, if i try excluding more than one folder the command won't run at all and gives an error that doesn't actually tell me what I did that was "wrong"

I gave up trying to do the search through the terminal and just did it through pcmanfm as the regular user account but that search didn't find the ROM either.

**Comment by bbbbbr** [comment]
Yes, looks like the game should be under: `~/game/main.gb`

ps. If you want a more flexible makefile, you could take a look at this one from the gbdk-2020 example folder:
https://github.com/gbdk-2020/gbdk-2020/tree/develop/gbdk-lib/examples/gb/template_subfolders
