### ISSUE TITLE
Floating points

### ISSUE THREAD

**Issue by Luxtech** [gbdk-2020/gbdk-2020#197]
I was wondering how to use floats, 
I read some where in the docs that floats are not supported. In the gbdk manual pdf there is stated that floating operations are supported/coming see page 30, 11.2.4 GBDK 2.95: 
```
7th July, 2000
Information on float and long support. Someone asked about the state of float/long support recently. Heres my
reply:
long support is partly there, as is float support. The compiler will correctly recognise the long and float keywords,
and will generate the code for most basic ops (+, -, &, | etc) for longs correctly and will generate the function calls
for floats and hard long operations ( ∗ , /, %) correctly. However it wont generate float constants in the correct format,
nor will it 'return' a long or float - gbdk doesn't yet support returning types of 4 bytes. Unfortunately its not going to
make it into 2.95 as there's too much else to do, but I should be able to complete long support for 2.96
```

Can someone clarify if I will be able to use floats with the gbdk compiler? If i use them currently `float = 3.14` the compiler gives an error:  
```
main.c:8: syntax error: token -> '=' ; column 7
make: *** [Makefile:29: PiBoy.gb] Error 1
```

I wanted to create a cool project for the gameboy, but not able to use floats stops the project. I am a bit of a beginner to C so if I am doing something wrong please help!

**Comment by bbbbbr** [comment]
The changelog note is from GBDK 2.95 in July of 2000, which is very old and is under "Historical GBDK Release Notes". It does not apply to modern GBDK-2020.

You can use floats, but keep in mind that they are inefficient on an 8 bit cpu such as the Game Boy's.

For your example, you need a variable name as well:
`float myVar = 3.14;`

**Comment by bbbbbr** [comment]
I was wrong about the above btw, sorry about that!

I had made a test program with floats in a way such that the SDCC optimizer performed all the calculations before compiling and removed the runtime ones. So it looked like it was working, but it actually wasn't.

It was possible to "use" floats as long as you didn't try to do anything with them. :)
