### ISSUE TITLE
Where do I point SDCCDIR to?

### ISSUE THREAD

**Issue by irishgreencitrus** [gbdk-2020/gbdk-2020#211]
I compiled sdcc, and i have the binaries however compiling gbtk-2020 is failing with this error. Where do i find sdcc-lib.h?
```
Building lib
for i in gbz80; do make port THIS=$i PORT=$i; done
rm -f  *.o *.cdb *.sym *.lst *~ *.asm
if [ -e global.s ]; then \
        sed -e "s/.NEAR_CALLS\W=\W[0-9]\+/.NEAR_CALLS = 1/" global.s > tmp1.txt ;\
        mv tmp1.txt global.s; \
fi
mkdir -p ../build/small/asxxxx/gbz80
/bin/sdcc -I../include -DSDCC_z80 -D__gbz80 -mgbz80 -DGBDK=1 --max-allocs-per-node 50000 -c -o ../build/small/asxxxx/gbz80/_mullong.o _mullong.c
_mullong.c:651:23: fatal error: sdcc-lib.h: No such file or directory
compilation terminated.
make[2]: *** [../libc/rules-asxxxx.mk:9: ../build/small/asxxxx/gbz80/_mullong.o] Error 1
make[1]: *** [Makefile:33: ports] Error 2
make: *** [Makefile:174: gbdk-lib-build] Error 2
```

**Comment by irishgreencitrus** [comment]
Fixed by installing doxygen and doing make clean then redoing make. Sorry!

**Comment by irishgreencitrus** [comment]
Ignore last comment. This still happens but slightly later on

**Comment by bbbbbr** [comment]
`SDCCDIR` should point to the SDCC folder which contains both `bin` (contains compiled sdcc related binaries) and `share` (contains `doc`, `man`, `sdcc`).

I haven't compiled it from scratch for a while, so the example below is using an SDCC release package. So you'd need to locate the equivalent.

For example:
`EXPORT SDCCDIR=/usr/home/someuser/sdcc/`

And the contents of that directory would look like:
```
$ ls -la /usr/home/someuser/sdcc/

drwxr-xr-x 2 someuser someuser  4096 Jun 10 23:15 bin
drwxr-sr-x 5 someuser someuser  4096 Jun 10 23:14 share
```

**Comment by untoxa** [comment]
i compiled SDCC from the trunk and then GBDK-2020 with that freshly compiled SDCC - it works perfectly. you only need to do how it is written in the readme.

**Comment by irishgreencitrus** [comment]
the share directory didn't compile for some reason

**Comment by untoxa** [comment]
you may try with this latest commit too: https://github.com/gbdk-2020/gbdk-2020/commit/3ef4db914e2c9ddea0ba22020bdac4fd2f951362
SDCC library dependences should be removed in it
