### ISSUE TITLE
floating point math

### ISSUE THREAD

**Issue by maxall41** [gbdk-2020/gbdk-2020#219]
Hi I'm making a game and I want the movement to be slower so i have to use a number less than 1 but greater than 0 so i have to use floating points according to this gbdk-2020 supports floats: https://www.gitmemory.com/issue/gbdk-2020/gbdk-2020/197/860796432. But when trying todo that i get this error:
```
?ASlink-Warning-Undefined Global '___fssub' referenced by module 'game'

?ASlink-Warning-Undefined Global '___fsadd' referenced by module 'game'

?ASlink-Warning-Undefined Global '___sint2fs' referenced by module 'game'

?ASlink-Warning-Undefined Global '___fs2sint' referenced by module 'game'
make: *** [game.gb] Error 1
```
Am i just using floats incorrectly or this post wrong?

code:
```

#include <gb/gb.h>
#include <stdint.h>
#include <gb/drawing.h>
#include "player_sprite.c"

UINT8 player[2];
UINT8 police[2];

const UINT8 player_speed = 1;
const float police_move_speed = 0.35;

void DrawPlayer(void) 
{
	set_sprite_data(0,2,PlayerSprite);
	set_sprite_tile(0,0);
	move_sprite(0,player[0],player[1]);
}

int follow_y(int current_pos_y,int target_pos_y)
{
	if (target_pos_y < current_pos_y) {
		return current_pos_y - police_move_speed;
	} else if (target_pos_y > current_pos_y) {
		return current_pos_y + police_move_speed;
	} else {
		return current_pos_y;
	}
}


int follow_x(int current_pos_x,int target_pos_x)
{
	if (target_pos_x < current_pos_x) {
		return current_pos_x - police_move_speed;
	} else if (target_pos_x > current_pos_x) {
		return current_pos_x + police_move_speed;
	} else {
		return current_pos_x;
	}
}

void DrawPolice(void) {
	set_sprite_data(0,2,PlayerSprite);
	set_sprite_tile(1,0);

	police[0] = follow_x(police[0],player[0]);
	police[1] = follow_y(police[1],player[1]);

	move_sprite(1,police[0],police[1]);
}



void main(void)
{
	player[0] = 88;
	player[1] = 77;

	police[0] = 80;
	police[1] = 60;

	SHOW_SPRITES;

	while(1) {
		switch(joypad()) {
			case J_LEFT:
				player[0] -= player_speed;
				break;
			case J_RIGHT:
				player[0] += player_speed;
				break;
			case J_UP:
				player[1] -= player_speed;
				break;
			case J_DOWN:
				player[1] += player_speed;
				break;
		}
		DrawPlayer();
		DrawPolice();
	};
}
```

**Comment by bbbbbr** [comment]
The link you provided misses the final comment on that thread where I correct my earlier comment. :)
https://github.com/gbdk-2020/gbdk-2020/issues/197

Floating point is not supported in GBDK-2020 (it is inefficient on the Game Boy cpu).

Instead you can use a 16 bit integer to simulate some decimal precision, and then downshift when you need to convert it to your coordinate system / whole numbers. Common allocations of the bits are (upper whole number:lower decimal) 12:4 or 8:8 and the whole number range would be similar as before. You would need to adjust the speed values you add and subtract depending on how many bits you downshift.

For example here is with 12:4 (you might want to make a `#define` value for the downshift amount)
```
uint16_t player[2];
...
player[0] -= player_speed;
...
move_sprite(0,player[0] >> 4,player[1] >> 4);
```

**Comment by Zal0** [comment]
There is also the "fixed" type on  https://github.com/hschmitt/gbdk/blob/master/include-gb/types.h

It's a fixed point 8:8 and you don't need to use displacement operations,  just access the high or low byte

**Comment by bbbbbr** [comment]
Good point, to demonstrate:
```
fixed player[2];
...
player[0].w -= player_speed; // Modify player position using it's 16 bit representation
...
move_sprite(0, player[0].b.h ,player[1].b.h); // Use only the upper 8 bits for setting the sprite
```

**Comment by untoxa** [comment]
that is not needed, @bbbbbr, because SDCC emits similar code that simply takes MSB for `(player[0].b >> 8)` and even for `(player[0].b / 256)`.
