### ISSUE TITLE
SDCC likely to change their calling convention

### ISSUE THREAD

**Issue by spth** [gbdk-2020/gbdk-2020#220]
SDCC is considering changing the calling convention for the next major release.

C code should just continue to work. However, asm code will have to be rewritten, or marked as continuing to use the old calling convention.

sdcc-user mailing list post:
https://sourceforge.net/p/sdcc/mailman/message/37328989/

SDCC feature request:
https://sourceforge.net/p/sdcc/feature-requests/732

Branch that implements the new convention:
https://sourceforge.net/p/sdcc/code/HEAD/tree/branches/breaktheworld/

**Comment by untoxa** [comment]
Hello Philipp,

Can you please have a look at this: https://sourceforge.net/p/sdcc/patches/396/
We tested that and it works very well. That will help much devkitSMS developers, 
and I am also implementing SMS/GG port of GBDK-2020 to make "GBStudio for game 
gear" project possible.

-- 
Best regards,
 Tony                            ***@***.***

**Comment by untoxa** [comment]
I'm already working on the library update. Waiting for SDCC daily builds though.

**Comment by bbbbbr** [comment]
Documenting the updates from toxa here, in addition to the sdcc ticketing system:

Some initial patches to use the old calling conventions for the time being
https://github.com/gbdk-2020/gbdk-2020/commit/a270bd69979fdd039e417258ebb5438a0484ce23
https://github.com/gbdk-2020/gbdk-2020/commit/0a28368ce3e3b9e1d8524a0624c06d9dbc153cae
https://github.com/gbdk-2020/gbdk-2020/commit/582fb3da2191bc46a5391f13893da28e08b775ac
https://github.com/gbdk-2020/gbdk-2020/commit/6569503c1124accbbd6b0fd0ca6e8ea42c0cd7e8

And a crash when building with SDCC nightly 12674 (which doesn't happen with 12539)
"GBZ80 SDCC segfault "
https://sourceforge.net/p/sdcc/bugs/3281/

**Comment by bbbbbr** [comment]
Note for myself: will need to update any GBDK docs about calling conventions

**Comment by bbbbbr** [comment]
#338 SDCC 4_2 branch merged into `develop`

The github actions on `develop` now build with SDCC 13350
