### ISSUE TITLE
sms/gg

### ISSUE THREAD

**Issue by bbbbbr** [gbdk-2020/gbdk-2020#225]
SDCC
- [x] gbz80 makebin: Turn off forced GB logo copy (**merged in  r12748**)
       https://sourceforge.net/p/sdcc/patches/395/
       https://sourceforge.net/p/sdcc/code/12748/
- [ ] sdldz80: sms/gg address translation (patch awaiting feedback)
       https://sourceforge.net/p/sdcc/patches/396/
- [x] sdasz80: support for .incbin directive (**patch merged**)
      https://sourceforge.net/p/sdcc/patches/398/
- [x] sdcc -mz80: allow -bo<N> -ba<N> switches (**merged in [[r13110]](https://sourceforge.net/p/sdcc/code/13110/)**)
      https://sourceforge.net/p/sdcc/patches/399/
- [ ] sdcc: #pragma dataseg <section name> (optional)
- [ ] sdasz80: in/out (<symbol>), A does not work when symbol is external, it emits in/out (0x00),A. that means that extern volatile __sfr name; does not work, only static volatile __sfr __at(<addr>) name; (optional)
- [x] sdcc: `info 218: z80instructionSize() failed to parse line node, assuming 999 bytes` `'b_some_banked_func	= 2'`  - (filed ticket, awiating further feedback) (Only the swap instruction handling bug mentioned in the ticket is fixed so far: r12680)
    https://sourceforge.net/p/sdcc/bugs/3280/ (fix by @basxto [[r13187]](https://sourceforge.net/p/sdcc/code/13187/)) 

- [x] sdasgb/z80: macOS macro symbol 80 character overflow (for emu_debug) (**patch merged**)
      https://sourceforge.net/p/sdcc/bugs/3277/  (workaround merged by @basxto [[12966]](https://sourceforge.net/p/sdcc/code/12966/)) 

LIB
- [x] stdio (at least fonts and printf)
- [x] check stdlib and unify function subset with GB
- [x] separate common headers subset (but not std), like incbin.h
- [x] Support sprite clipping for metasprites on SMS (same as how NES metasprite drawing does it)

LCC
- [x] Class entries (`z80:sms`, `z80:gg`)
- [x] Alternate linker default flags (`fixllist`)
       #224
- [x] Enable auto-banking `lcc` + `bankpack` 
       #223 

Build Env
- [x] Build for multiple Ports / Platforms and copy to output

Tools
- [x] png2asset: different OAM (SAT) format: without properties byte
- [x] png2asset:  support for 4bpp tiles

**Comment by untoxa** [comment]
@spth Philipp, can you please help us with these very few remaining patches, that are waiting to be merged into SDCC? Thank you!

**Comment by untoxa** [comment]
i close as "completed", despite the two minor things:
- sdcc: #pragma dataseg <section name> (optional)
- sdasz80: in/out (<symbol>), A does not work when symbol is external, it emits in/out (0x00),A. that means that extern
