### ISSUE TITLE
Titlescreen doesn't start from main

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [gbdk-2020/gbdk-2020#226]
My game's titlescreen doesn't work if I try to start it from void main(){ } but it will work when started from checkinput with the start button, this is most of my code from main.c: 

`#include <C:/gbdk-win/include/gb/gb.h>
//include </opt/gbdk/include/gb/gb.h>
#include <C:/gbdk-win/include/rand.h>
//#include </opt/gbdk/include/rand.h>
#include "bg.c"
#include "sprites.c"
#include "music.c"
#include "sound.c"
//#include "maps.c"
//#include "Checksum_calculator.asm"
//#include "drm.c"
#include "titlescreen_bg.c"
#include "titlescreen_win.c"
#include "menu_bg.c"

#define GS = 0xC000,
#define player_pos_x_hb = 0xC001,
#define player_pos_x_lb = 0xC002,
#define player_pos_y_hb = 0xC003,
#define player_pos_y_lb = 0xC004,
#define map_num_hb = 0xC005,
#define map_num_lb = 0xC006,
#define player_level = 0xC007,
#define player_max_health_points = 0xC008,
#define player_heath_points = 0xC009,
#define player_max_magic_points = 0xC00A,
#define player_magic_points = 0xC00B,
#define player_str = 0xC00C,
#define player_atk = 0xC00D,
#define player_def = 0xC00E,
#define player_class = 0xC00F,
#define enim_spawn_r = 0xC010,
#define enim_1_level = 0xC011,
#define enim_2_level = 0xC012,
#define enim_3_level = 0xC013,
#define enim_4_level = 0xC014,
#define enim_1_max_health_points = 0xC015,
#define enim_2_max_health_points = 0xC016,
#define enim_3_max_health_points = 0xC017,
#define enim_4_max_health_points = 0xC018,
#define enim_1_health_points = 0xC019,
#define enim_2_health_points = 0xC01A,
#define enim_3_health_points = 0xC01B,
#define enim_4_health_points = 0xC01C,
#define enim_1_max_magic_points = 0xC01D,
#define enim_2_max_magic_points = 0xC01E,
#define enim_3_max_magic_points = 0xC01F,
#define enim_4_max_magic_points = 0xC020,
#define enim_1_magic_points = 0xC021,
#define enim_2_magic_points = 0xC022,
#define enim_3_magic_points = 0xC023,
#define enim_4_magic_points = 0xC024,
#define enim_1_str = 0xC025,
#define enim_2_str = 0xC026,
#define enim_3_str = 0xC027,
#define enim_4_str = 0xC028,
#define enim_1_atk = 0xC029,
#define enim_2_atk = 0xC02A,
#define enim_3_atk = 0xC02B,
#define enim_4_atk = 0xC02C,
#define enim_1_def = 0xC02D,
#define enim_2_def = 0xC02E,
#define enim_3_def = 0xC02F,
#define enim_4_def = 0xC030,
#define enim_1_type = 0xC031,
#define enim_2_type = 0xC032,
#define enim_3_type = 0xC033,
#define enim_4_type = 0xC034,

void main() {

DISPLAY_ON;                         // Turn on LCD

	while(1) {
		checkInput();				// Check buttons
		wait_vbl_done();			// Wait until VBLANK to avoid corrupting VRAM
	}

}

 void checkInput() {

	if (joypad() & J_A) {
		// A button
 }
    if (joypad() & J_B) {
		// B button
 }
	if (joypad() & J_START) {
		// Start button
		titlescreen();
 }
	if (joypad() & J_SELECT) {
		// Select button
 }
	if (joypad() & J_UP) {
		// D-pad up
 }
	if (joypad() & J_DOWN) {
		// D-pad down
 }
	if (joypad() & J_LEFT) {
		// D-pad left
 }
	if (joypad() & J_RIGHT) {
		// D-pad right
 }
}

void titlescreen() {

	SHOW_BKG;
//	SHOW_WIN;

	VBK_REG = 0;
	
	set_bkg_data(0, 127, bg); // Load game title, ROM version, text boxes and numbers/letters/symbols tiles into BG mem
	set_bkg_tiles(0, 0, 20, 18, titlescreen_bg); // Load background layer map for titlescreen from titlescreen_bg and show it

//	VBK_REG = 0;
//
//	set_win_data(0, 127, bg); // Load game title, ROM version, text boxes and numbers/letters/symbols tiles into WIN mem 
//	set_win_tiles(0, 0, 12, 3, titlescreen_win); // Load window layer map for titlescreen from titlescreen_win and show it
//
//scroll_win(40, -48);

if (joypad() & J_START) {
	main_menu();
 }
else if (joypad() & J_A) {
	main_menu();
 }
else {
//	HIDE_WIN;
	titlescreen();
 }

}

void main_menu() {

SHOW_BKG;
SHOW_SPRITES;

	VBK_REG = 0;

	set_bkg_data(0, 127, bg);
	set_bkg_tiles(0, 0, 20, 18, menu_bg);

	set_sprite_data(0, 1, menu_arrow);      // Load the 'sprites' tiles into sprite mem

	set_sprite_tile(0,0);               // Set the first movable sprite (0) to be the first tile in the sprite mem (0)
	
	menu_arrow[0] = 80;
	menu_arrow[1] = 72;

if (joypad() & J_UP) {
	 sound_move();
 }
else if (joypad() & J_DOWN) {
	 sound_move();
 }
else if (joypad() & J_A) {
	sound_select();
 }
else {
	sound_back();
	titlescreen();
 }
}`

when this compiles it works like it's supposed to but the start button can not be used for anything else so I tried moving the code that tells the game to run the titlescreen into `void main() { }` but that does not work at all, I've tried putting it before `DISPLAY_ON;`, putting it after `DISPLAY_ON` and putting it in the while loop, in the while loop the titlescreen displays after the ROM loads but all it wants to do is show the titlescreen and putting it before or after `DISPLAY_ON;` won't start the title screen after the ROM loads, I tried using the `void init() { }` but that didn't work either so I removed the `void init () { }` because I don't need it for anything else (all it was doing was running update_switches(); which I don't need now), this could be a problem with how i coded this but it could be a problem with gbdk.

**Comment by untoxa** [comment]
it is not a GBDK-2020 problem, you have a problem with common program design. GBDK-2020 issues is not a right place to troubleshoot your game, you can either ask on one of the dedicated forums, gbdk-2020 discord or any other resource where C developers share solutions.
