### ISSUE TITLE
set_tiles() always crashes (rst $38 loop)

### ISSUE THREAD

**Issue by GreenAndEievui** [gbdk-2020/gbdk-2020#232]
`set_tiles`, no matter when it's used or what arguments it's given, will cause the Game Boy to get stuck in an `rst $38` loop. I took a look at the source for the function and it seems to be caused by a few mistakes:

- The first `PUSH DE` is without a corresponding `POP` to balance the stack. 
- The arguments are being read incorrectly as well, it looks like it should be `LDHL SP, #8` and `#14`, not `#7` and `#13`. 
- `.set_xy_tt` is also clearly not meant to be called. It seems to be expecting the width and height off the stack, but when called it just ends up popping the return value.

I wrote a very simple replacement in C that could be used instead if GBDK had a vmemcpy function:
```
void set_tiles(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t *vram_addr, const uint8_t *tiles) NONBANKED
{
        vram_addr += x + y * 32;
	for (; h; h--) {
		vmemcpy(vram_addr, w, tiles);
		vram_addr += 0x20;
		tiles += w;
	}
}
```

**Comment by untoxa** [comment]
thank you for the report. test:
```c
#include <gb/gb.h>
const unsigned char pattern1[] = {0x80,0x80,0x40,0x40,0x20,0x20,0x10,0x10,0x08,0x08,0x04,0x04,0x02,0x02,0x01,0x01};
const unsigned char pattern2[] = {0x00,0x00,0x7E,0x7E,0x40,0x40,0x54,0x54,0x48,0x48,0x54,0x54,0x40,0x40,0x00,0x00};
const unsigned char map[]      = {0x20,0x21,0x21,0x20};
void main() {
    SHOW_BKG;
    set_bkg_data(0x20, 1, pattern1);
    set_bkg_data(0x21, 1, pattern2);
    set_tiles(10, 5, 2, 2, (UBYTE *)0x9800, map);
}
```

**Comment by untoxa** [comment]
ps: your suggested function is not equivalent, because it does not support wrapping, while set_tiles() does; GBDK-2020 does have "vmemcpy" which is set_data(); here you can find reference for GBDK-2020 functions: https://gbdk-2020.github.io/gbdk-2020/docs/api/
