### ISSUE TITLE
Github Workflows & CI / CD 

### ISSUE THREAD

**Issue by bbbbbr** [gbdk-2020/gbdk-2020#241]
Opening this issue as a place to continue the conversation from #240 with @wujood  

Mirroring last commend from that thread here since it's a good starting point:
> **wujood:**
> I would suggest the following:
> 
>     * Create a workflow that builds the project on each push on every branch to validate the integrity of the changes.
> 
>     * Create a workflow that builds and publishes the binaries if a release is created.
> 
>     * In addition to the binaries you should create a docker image that has the latest binaries installed and is ready to compile gbdk projects.
> 
> 
> That way developers can create workflows and GitHub actions while using the latest docker image. I could provide help if you help me create the scripts to actually build the binaries.
> 
> I noticed that you had a workflow with a lot of if-statements for the different platforms. I would suggest to split them into different files if you have almost nothing in common to keep the overhead small and isolate bugs faster.

**Comment by bbbbbr** [comment]
These all sounds good.

I'd been hoping that the Windows build would be closer to the Linux / macOS builds, but yeah it didn't work out that way. Unless you see some ways where they could be brought together. The actual build stage is essentially the same- it's the setup, environment var setting and packaging format which differ.

Lower priority than the others- it might be useful to have a workflow to regenerate to documentation and check that in.
*  Not for every commit, but for release + manually triggered to for review before release
* install doxygen + the repo
* run a couple of the make targets (`docs-toolchain-generate`, `doxygen-generate`, `doxygen-generate-with-pdf`)
* commit the updated docs to the repo

**Comment by wujood** [comment]
For docker it should be enough to support a build inside a ubuntu environment, or are there significant differences between those platforms for the end result. Of course this ubuntu image should be supported on all platforms (win/Mac/linux).

**Comment by wujood** [comment]
> These all sounds good.
> 
> I'd been hoping that the Windows build would be closer to the Linux / macOS builds, but yeah it didn't work out that way. Unless you see some ways where they could be brought together. The actual build stage is essentially the same- it's the setup, environment var setting and packaging format which differ.
> 
> * Lower priority than the others- it might be useful to have a workflow to regenerate to documentation and check that in.
>   
>   * Not for every commit, but for release + manually triggered to for review before release
>   * install doxygen + the repo
>   * run a couple of the make targets (`docs-toolchain-generate`, `doxygen-generate`, `doxygen-generate-with-pdf`)
>   * commit the updated docs to the repo

Generating the docs and pushing them automatically requires a personal access token that has write access to the repository. Whoever generated this access token will be set as the author of those commits. You could use the gbdk-2020 account for that, create a new account especially for this task or use a personal access token from your account. 

Once a release is created it would be too late to generate the docs for the release tag. A manual trigger is a good starting point, I guess.
