### ISSUE TITLE
makebin fails to convert noi to sym correctly when issued with -yS

### ISSUE THREAD

**Issue by untoxa** [gbdk-2020/gbdk-2020#276]
Something goes wrong and 46 kilobyte noi files is converted into 8 kilobyte sym, and 3/4 of symbols simply not transferred. Tool also filters out symbols that begin with `l__` and `.__.ABS.` which is strange and useless, conversion must be 1:1.

**Comment by bbbbbr** [comment]
Patch with fix submitted to SDCC:
https://sourceforge.net/p/sdcc/patches/400/
