### ISSUE TITLE
gbdk-4.0.5: WINDOWS Binaries - makebin.exe reported by Windows Defender as Win32/Uwamson.A!ml

### ISSUE THREAD

**Issue by sttng** [gbdk-2020/gbdk-2020#277]
I think it might be a false positive, but I guessed better to report - didn't have this with gbdk-4.0.3 or gbdk-4.0.4

Details from Windows Defender:

Program:Win32/Uwamson.A!ml

Alert level: Low
Status: Active
Date: 10/14/2021 10:58 AM
Category: Potentially Unwanted Software
Details: This program has potentially unwanted behavior.

Affected items:
file: C:\Users\myuser\Documents\gbdk\bin\makebin.exe

**Comment by bbbbbr** [comment]
makebin has been rebuilt (with minor, unrelated code changes: add `-yN` flag) and no longer seems to trigger virus warnings. The GBDK-2020 4.0.5 release has been updated with it.

See the 4.0.6 SDCC binary package for standalone binaries.
