### ISSUE TITLE
BGB macro documentation

### ISSUE THREAD

**Issue by victorheringer** [gbdk-2020/gbdk-2020#288]
Hello,

Maybe I'm missing something but BGB_MESSAGE_FMT uses sprintf so stdio.h should be included right? If so, would be nice to have this tip in the docs.

**Comment by untoxa** [comment]
well, bgb_emu.h does not depend on stdio.h, you can use all functions from that header without including of stdio.h.

what version of GBDK-2020 are you using?

**Comment by victorheringer** [comment]
I'm using gbdk-4.0.3, looks like BGB_MESSAGE_FMT was [replaced](https://github.com/gbdk-2020/gbdk-2020/commit/7b94d3fe4553f9ef8e6d635edec22e381588c321#diff-ae73f586ddc3cf8c504fc982ec321a4e3c937603f53f0e38ec3d9eb6cacff2b3) in recent versions :sweat_smile:  I'll update to gbdk-4.0.5 and close the issue, thanks for helping!
