### ISSUE TITLE
build rom with hugedriver on ubuntu 20.04

### ISSUE THREAD

**Issue by jackygoule** [gbdk-2020/gbdk-2020#296]
Hello i want to build a rom with a song and hugedriver on ubuntu.
i make a folder with template_minimal with gbdk_palyer_exemple.c and sample_song.c and i put hugedriver .h and i rename gbdk_palyer_exemple.c to main.c
when i make:
:../../../bin/lcc  -o Example.gb main.c sample_song.c 
main.c:
sample_song.c:
sample_song.c:1051: warning 158: overflow in implicit constant conversion

?ASlink-Warning-Undefined Global '_hUGE_dosound' referenced by module 'main'

?ASlink-Warning-Undefined Global '_hUGE_mute_channel' referenced by module 'main'

?ASlink-Warning-Undefined Global '_hUGE_init' referenced by module 'main'
make: *** [Makefile:29 : Example.gb] Erreur 1

In the doc : is it possible to make a tuto for this ?
Thanks for your help

**Comment by untoxa** [comment]
It is not a gbdk-2020 issue.
