### ISSUE TITLE
misspelling in gbdk-lib/include/gb/crash_handler.h

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [gbdk-2020/gbdk-2020#300]
I have found what might be a mistake in the crash handler and have fixed it on my own computer and the crash handler still works fine in my game with some bad code that I wrote but I cannot change the file here without forking

the original file says:
`/** @file gb/crash_handler.h
    When crash_handler.h is included, a crash dump screen
    will be displayed if the CPU executes uninitalized
    memory (with a value of 0xFF, the opcode for RST 38).
    A handler is installed for RST 38 that calls
    @ref __HandleCrash().
    \code{.c}
    #include <gb/crash_handler.h>
    \endcode
    Also see the crash example project included with gbdk.
*/
#ifndef __CRASH_HEANDLER_INCLUDE
#define __CRASH_HEANDLER_INCLUDE

/** Display the crash dump screen.
    See the intro for this file for more details.
*/
void __HandleCrash();
static void * __CRASH_HEANDLER_INIT = &__HandleCrash;

#endif`

it should say:
`/**` @file gb/crash_handler.h

    When crash_handler.h is included, a crash dump screen
    will be displayed if the CPU executes uninitalized
    memory (with a value of 0xFF, the opcode for RST 38).
    A handler is installed for RST 38 that calls
    @ref __HandleCrash().

    \code{.c}
    #include <gb/crash_handler.h>
    \endcode

    Also see the crash example project included with gbdk.
*/
#ifndef __CRASH_HANDLER_INCLUDE
#define __CRASH_HANDLER_INCLUDE

/** Display the crash dump screen.

    See the intro for this file for more details.
*/
void __HandleCrash();
static void * __CRASH_HANDLER_INIT = &__HandleCrash;

#endif`

this isn't a problem because the program still works fine it's just something I found while looking at the main.asm file for my project and I am only posting this as an issue instead of fixing it myself because I do not have permissions to edit the file.

**Comment by untoxa** [comment]
thank you, fixed.
