### ISSUE TITLE
SDCC Error

### ISSUE THREAD

**Issue by unutilisateurdegoogle** [gbdk-2020/gbdk-2020#301]
I want to compile my GB game but it won't work because it "don't" find /sdcc

This the log : 
`lcc.exe: "C:\users\administrateur\onedrive\bureau\bin/sdcc": No such file or directory` 
With gcc : 
`root@MSI:/mnt/c/users/administrateur/onedrive/bureau/gb - c# gcc -Wall --debug -DUSE_SFR_FOR_REG -o main.gb main.o
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function _start':
(.text+0x24): undefined reference to main
collect2: error: ld returned 1 exit status`

But i can access by Windows Explorer

**Comment by bbbbbr** [comment]
Follow the instructions in getting started, including building the samples. First make sure the samples build, whether it is using `make` or `compile.bat`. Then start a project based off the templates.
https://gbdk-2020.github.io/gbdk-2020/docs/api/docs_getting_started.html

You cannot use `gcc` to build GBDK-2020 based projects (or any kind of code for the Game Boy ).
