### ISSUE TITLE
'make' command not working

### ISSUE THREAD

**Issue by PG24Official** [gbdk-2020/gbdk-2020#302]
C:\gbdk\examples\gb>make
'make' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bbbbbr** [comment]
If you are on Windows use `compile` or `compile.bat` instead.

This was updated in the docs a while ago but has not yet rolled out.
https://github.com/gbdk-2020/gbdk-2020/commit/a6c581e3eacd7aa3ed64824082318ec28b5bf0f9#diff-85da6ebc82effd6264a2a6611d8950d3ed641f525027abb404c0748c03612112
