### ISSUE TITLE
__GBDK_VERSION is still 405 in the 4.0.6 release

### ISSUE THREAD

**Issue by reini1305** [gbdk-2020/gbdk-2020#316]
I wanted to adapt my usage of `arand()` to the new behavior in 4.0.6 by checking the GBDK version but realized that it is still equal to 405 in the 4.0.6 release.

**Comment by bbbbbr** [comment]
Thanks, we missed that. I'll run a new CI build for you to test with:
https://github.com/gbdk-2020/gbdk-2020/actions/runs/1786217607

**Comment by bbbbbr** [comment]
I've updated the release with the CI build binaries
