### ISSUE TITLE
Error When Compile

### ISSUE THREAD

**Issue by dinaradenis** [gbdk-2020/gbdk-2020#324]
When I Tried To Compile The GB Example, It Show This Error:

root@localhost:/opt/gbdk/examples/gb# make
make -C banks/.
make[1]: Entering directory '/opt/gbdk/examples/gb/banks'
../../../bin/lcc -Wa-l -Wl-m -Wl-j -c -o banks.o banks.c
make[1]: ../../../bin/lcc: Permission denied
make[1]: *** [Makefile:12: banks.o] Error 127
make[1]: Leaving directory '/opt/gbdk/examples/gb/banks'
make: *** [Makefile:14: banks/.] Error 2

I Try To Make The LCC File Executable, But Still Don't Work. Any Idea?

**Comment by untoxa** [comment]
Permission denied. All files in /opt/gbdk/bin must have +x attribute.

**Comment by dinaradenis** [comment]
I Already Tried To Do That, But Give Me An Error "No Such Files Or Directory"

**Comment by dinaradenis** [comment]
This Is The Error:

root@localhost:~# cd gbdk
root@localhost:~/gbdk# cd bin
root@localhost:~/gbdk/bin# chmod +x *
root@localhost:~/gbdk/bin# ls
bankpack    makebin    sdasgb   sdcpp    sdobjcopy
gbcompress  packihx    sdasz80  sdldgb   sdranlib
ihxcheck    png2asset  sdcc     sdldz80  sz80
lcc         sdar       sdcdb    sdnm
root@localhost:~/gbdk/bin# cd
root@localhost:~# cd gbdk
root@localhost:~/gbdk# cd examples
root@localhost:~/gbdk/examples# cd gb
root@localhost:~/gbdk/examples/gb# make
make -C banks/.
make[1]: Entering directory '/root/gbdk/examples/gb/banks'
../../../bin/lcc -Wa-l -Wl-m -Wl-j -c -o banks.o banks.c
make[1]: ../../../bin/lcc: No such file or directory
make[1]: *** [Makefile:12: banks.o] Error 127
make[1]: Leaving directory '/root/gbdk/examples/gb/banks'
make: *** [Makefile:14: banks/.] Error 2

**Comment by dinaradenis** [comment]
This is The Error:

root@localhost:~# cd gbdk
root@localhost:~/gbdk# cd bin
root@localhost:~/gbdk/bin# chmod +x *
root@localhost:~/gbdk/bin# ls
bankpack    makebin    sdasgb   sdcpp    sdobjcopy
gbcompress  packihx    sdasz80  sdldgb   sdranlib
ihxcheck    png2asset  sdcc     sdldz80  sz80
lcc         sdar       sdcdb    sdnm
root@localhost:~/gbdk/bin# cd
root@localhost:~# cd gbdk
root@localhost:~/gbdk# cd examples
root@localhost:~/gbdk/examples# cd gb
root@localhost:~/gbdk/examples/gb# make
make -C banks/.
make[1]: Entering directory '/root/gbdk/examples/gb/banks'
../../../bin/lcc -Wa-l -Wl-m -Wl-j -c -o banks.o banks.c
make[1]: ../../../bin/lcc: No such file or directory
make[1]: *** [Makefile:12: banks.o] Error 127
make[1]: Leaving directory '/root/gbdk/examples/gb/banks'
make: *** [Makefile:14: banks/.] Error 2

**Comment by dinaradenis** [comment]
It Give Me This Error:

root@localhost:~/gbdk/examples/gb# make
make -C banks/.
make[1]: Entering directory '/root/gbdk/examples/gb/banks'
../../../bin/lcc -Wa-l -Wl-m -Wl-j -c -o banks.o banks.c
make[1]: ../../../bin/lcc: No such file or directory
make[1]: *** [Makefile:12: banks.o] Error 127
make[1]: Leaving directory '/root/gbdk/examples/gb/banks'
make: *** [Makefile:14: banks/.] Error 2

I Already Make All File In GBDK Folder Executable.

**Comment by untoxa** [comment]
that is not a gbdk-2020 issue. make sure `/opt/gbdk/bin/lcc` (and all other files in `opt/gbd/bin`) has executable attribute and runs when you type `lcc`.
