### ISSUE TITLE
SDCC 4.2.0 has no gbz80 port

### ISSUE THREAD

**Issue by jellelicht** [gbdk-2020/gbdk-2020#330]
From the SDCC mailing list announcement for 4.2.0:
> * The gbz80 port was renamed to sm83.

**Comment by untoxa** [comment]
SDCC 4.2 is not yet supported.

**Comment by untoxa** [comment]
we already have similar opened issue

**Comment by jellelicht** [comment]
Thanks, mentioned this ticket over there, as there was no mention of this specific issue yet.
