### ISSUE TITLE
png2asset: Add flags to specify which parts should be in the generated output when creating a map.

### ISSUE THREAD

**Issue by HerrZatacke** [gbdk-2020/gbdk-2020#345]
When running png2asset with the `-map`-flag, the resulting code contains some artifacts which may not be required for every use-case:
* `const uint8_t test_tile_pals[93] = {...}` is quite a huge chunk of data and (as toxa mentioned "ZGB specific stuff") 
* `const palette_color_t test_palettes[4] = {...}` may not be required for a DMG target
* `#include <gbdk/metasprites.h>` may not be required/necessary at all for a tilemap.

Suggestion: add a flag like `-no-color` or `-dmg` to omit the palette information.

**Comment by untoxa** [comment]
https://github.com/gbdk-2020/gbdk-2020/commit/ffe934a8435f65493b47585de49edec75a15b373

**Comment by tumetuoppi** [comment]
Bump as I encountered this issue as well when developing a DMG game.

- The includes are a bit weird. <gbdk/metasprites.h> does not seem to be necessary, neither is <gbdk/platform.h>, but <gb/cgb.h> is needed by const palette_color_t whatever_palettes[4] and it's not added automatically
- Visual Studio Code seems to also have an issue with the BANKREF being in there. Seems to compile fine though so this could be just a configuration issue on my end.

In general it would be nice to have a "DMG only" option flag.

**Comment by bbbbbr** [comment]
Agree that an option to suppress the palette data would be useful. I will add it to my list of things to look into.
 
With regard to `gb/cgb.h` , the use of `platform.h` will automatically include it when the current target is the Game Boy (or AP or Mega Duck).
https://github.com/gbdk-2020/gbdk-2020/blob/develop/gbdk-lib/include/gbdk/platform.h#L4

**Comment by bbbbbr** [comment]
Implementing as a slight variation on version by @tumetuoppi from this commit:
https://github.com/tumetuoppi/gbdk-2020/commit/109183ef8bde51c675031a045edf8223bf7079f9
