### ISSUE TITLE
Lack of crt0.lst in gbdk-lib installation prevents use of -u linker option

### ISSUE THREAD

**Issue by michel-iwaniec** [gbdk-2020/gbdk-2020#351]
gbdk-lib/libc/rules-asxxxx.mk invokes the assembler with the -l option, to enable .lst files.

These .lst files can be converted into .rst files at link time, which show the final addresses after address relocation - a useful feature for debugging a user's code.

However, the installation step currently omits the .lst file for crt0.o, creating two problems:

1) There's no easy way for the user of gbdk to obtain source-vs-assembly debug information for the crt0 module.

2) More crucially, enabling the -u linker flag will actually cause a linker error, aborting the entire build process even when the intention was just to get .rst files for the user's own code.

In effect, this requires a user of gbdk to rebuild gbdk-lib from scratch if they ever want to build their applications with .rst files for debugging purposes.

A 1-line change to the top-level Makefile fixes this issue, by copying the crt0.lst file to the installation directory along with the crt0.o file.

**Comment by untoxa** [comment]
Hmmm… there is a -j option that obtain the *.NOI file which contain the final addresses of all public symbols. Also there is -m -w for the “wide map” extended map-file. What is the specific need for those RST files?

**Comment by michel-iwaniec** [comment]
> Hmmm… there is a -j option that obtain the *.NOI file which contain the final addresses of all public symbols. Also there is -m -w for the “wide map” extended map-file. What is the specific need for those RST files?

The .noi and .map files also contain some information - and I personally wouldn't be against installing these as well.

But they aren't really a replacement for the .lst / .rst files. These contain a full disassembly of the module, along with C source lines for the generated code.

I personally find these text files extremely helpful to keep on a second display when debugging code in Mesen's debugger, which AFAIK doesn't support any of the debug formats that sdcc spits out for source-level debugging. And I'm sure other people may have similar issues.

The relocated .rst files are a significant improvement here compared to the .lst files, as you don't need to do address-translation in your head as you cross-reference between debugger / text file.

And on top of that, it's nice to remove the obstacle for users who do want .rst files for their *own* code. At the moment they have to edit the gbdk Makefiles and rebuild gbdk themselves to achieve this. Adding the crt0.lst might seem redundant, but is the simplest way to fix the problem right now.

**Comment by untoxa** [comment]
If you pass -debug into lcc, then labels for each of the line of c code will be emitted into the noi (and sym with -Wm-S).

**Comment by untoxa** [comment]
Also take a look at .cdb files.

**Comment by untoxa** [comment]
fixed: https://github.com/gbdk-2020/gbdk-2020/commit/24fc5273c0cd4838a8d538f0602489cd1995ae30

**Comment by michel-iwaniec** [comment]
> If you pass -debug into lcc, then labels for each of the line of c code will be emitted into the noi (and sym with -Wm-S).

That may be useful for somebody, but is in no way a replacement for the utility of the .rst files which provide a full disassembly-with-C-source-code that can be cross-referenced with the disassembly of a debugger.

**Comment by michel-iwaniec** [comment]
> Also take a look at .cdb files.

There's nothing to look at, as they appear to always be zero-sized. Unless zero-sized files is the actual goal here?

**Comment by untoxa** [comment]
did you pass `-debug` on the compiling stage as well, not only on the linking stage?
