### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by nygator** [gbdk-2020/gbdk-2020#397]
Hi,

I just found out that the API documentation has some broken links. 
docs_links_and_tools.html has a link to "Awesome Game Boy Development list", which is broken (404)
docs_coding_guidelines.html has a link to "Game Boy games in C", which is also broken (404)

**Comment by bbbbbr** [comment]
Thanks for mentioning those. They were fixed with PR #354 but the changes won't take effect until the next release.
