### ISSUE TITLE
Let png2asset accept list of files

### ISSUE THREAD

**Issue by hbons** [gbdk-2020/gbdk-2020#422]
I have a target defined in my Makefile to generate the sprite data from PNGs. This was a bit tricky as png2asset doesn't accept a list of files. I came up with the following:

```make
sprites:
	for i in $(RESDIR)/*.png; do \
		$(GBDK_HOME)/bin/png2asset $$i; \
	done
```

It would be nice and also easier for new users to be able to set it up like this:

```make
sprites:
	$(GBDK_HOME)/bin/png2asset *.png
```

This could even be a (commented out) target in the existing templates. :)

**Comment by bbbbbr** [comment]
Yes, I can see it being useful for Windows (without Makefile support installed) and for users who are less familiar with Makefiles. `png2asset` is not well structured for this right now and would need additional code improvements before this kind of thing might be added cleanly.

In the mean time, below are some other options for Makefiles in a couple of the GBDK example projects. The benefit of using their approaches is it should only convert/rebuild files that have been updated as needed.

https://github.com/gbdk-2020/gbdk-2020/blob/master/gbdk-lib/examples/gb/metasprites/Makefile
https://github.com/gbdk-2020/gbdk-2020/blob/master/gbdk-lib/examples/cross-platform/logo/Makefile
https://github.com/gbdk-2020/gbdk-2020/blob/master/gbdk-lib/examples/cross-platform/metasprites/Makefile
https://github.com/gbdk-2020/gbdk-2020/blob/4316aebb656dc683a8367bcca1313a6a7001610e/gbdk-lib/examples/gb/apa_image/Makefile
