### ISSUE TITLE
lcc -E not working

### ISSUE THREAD

**Issue by asiekierka** [gbdk-2020/gbdk-2020#423]
test.c contents:

```
test_value = __SDCC_VERSION_MAJOR;
```

Expected behaviour:

```
[asie nelua-lang]$ /opt/gbdk/bin/lcc
# ...
-E	run only the preprocessor on the named C programs and unsuffixed files
# ...
[asie nelua-lang]$ /opt/gbdk/bin/sdcc test.c
test.c:1: error 1: Syntax error, declaration ignored at 'test_value'
test.c:1: syntax error: token -> '=' ; column 12
[asie nelua-lang]$ /opt/gbdk/bin/sdcc -E test.c
# 1 "test.c"
# 1 "<built-in>"
# 1 "<command line>"
# 1 "test.c"
test_value = 4;
```

Actual behaviour: 

```
[asie nelua-lang]$ /opt/gbdk/bin/lcc -E test.c
test.c:1: error 1: Syntax error, declaration ignored at 'test_value'
test.c:1: syntax error: token -> '=' ; column 12
```

This method is used by some tools ([example](https://github.com/edubart/nelua-lang)) to gather information about the C compiler.

**Comment by bbbbbr** [comment]
Sure, no problem to have lcc replace `-c` with `-E` for SDCC (when `-E` is specified to lcc). (Similar to how `-S` is handled)

Some implementation questions though:
1. Does the preferred resolution to this also include emitting the preprocessor output to:
   - stdout?
   - To a file (if specified with `-o`)?
   - Or gcc `-save-temps` like behavior where output is written to matching `.i` files if requested?

2. If yes to `-o` support: with multiple source files specified what is it expected?

-------
Right now:
- The output does not go to stdout
- It only goes to a temp file (that gets deleted) even with -o specified
- Output to `.i` files is suppressed (behavior inherited from the original code base)

With just allowing it to substitute `-E` it looks like:
```
 $ ../../../bin/lcc -E test.c
(shows no output in terminal)
```

With verbose on:
```
$ ../../../bin/lcc -v -E test.c
../../../bin/lcc $Id: lcc.c,v 2.0 2022/10/14 19:44:56 gbdk-2020 Exp $
"../../../"bin/sdcc -msm83 --no-std-crt0 --fsigned-char --use-stdout -D__PORT_sm83 -D__TARGET_gb -Wa-pogn -I"../../../"lib/gb -DINT_16_BITS -I"../../../"include -E test.c -o /tmp/lcc2393470.o
rm /tmp/lcc2393470.adb /tmp/lcc2393470.o /tmp/lcc2393470.asm /tmp/lcc2393470.lst /tmp/lcc2393470.sym
```

With verbose + output to a `.i` file (blocked)
```
$ ../../../bin/lcc -v -E test.c -o test.i
../../../bin/lcc $Id: lcc.c,v 2.0 2022/10/14 19:44:56 gbdk-2020 Exp $
../../../bin/lcc: -o would overwrite test.i  <-- (There is no actual test.i file to overwrite)
```

With verbose + output to a `.temp` file:
```
$ $ ../../../bin/lcc -v -E test.c -o test.temp
../../../bin/lcc $Id: lcc.c,v 2.0 2022/10/14 19:44:56 gbdk-2020 Exp $
"../../../"bin/sdcc -msm83 --no-std-crt0 --fsigned-char --use-stdout -D__PORT_sm83 -D__TARGET_gb -Wa-pogn -I"../../../"lib/gb -DINT_16_BITS -I"../../../"include -E test.c -o /tmp/lcc2420180.o
rm /tmp/lcc2420180.adb /tmp/lcc2420180.o /tmp/lcc2420180.asm /tmp/lcc2420180.lst /tmp/lcc2420180.sym
```

**Comment by asiekierka** [comment]
I have no particular preference, I just wanted to highlight that the advertised feature does not work at all. Based on NeLua's experience, it seems that most C compilers print to stdout when given `-E`, but the zcc wrapper from z88dk instead creates a `.c.i` files, and cc65 creates a `.i` file.

**Comment by bbbbbr** [comment]
When you have a moment please try out the changes in #426.

- `-E`
  - Goes to stdout by default (`.c` and `.h` files only)
  - Adding `--save-preproc` will output to matching `.i` files instead
  - Multiple files may be specified
  - No lcc `-o` single output file is supported

A build is here if that's convenient:
https://github.com/gbdk-2020/gbdk-2020/actions/runs/3271632514

**Comment by asiekierka** [comment]
Works great, thank you!
