### ISSUE TITLE
Include nixpkg derivation

### ISSUE THREAD

**Issue by AlexDalt** [gbdk-2020/gbdk-2020#447]
Would be great to fold this into nixpkg. I've written a `default.nix` file which _almost_ works.

```nix
{ pkgs ? import <nixpkgs> {} }:

let inherit (pkgs) lib stdenv fetchurl;
in stdenv.mkDerivation rec {
  version = "4.1.1";
  name = "gbdk";
  os = if stdenv.isDarwin then "macos" else "linux64";

  src = fetchurl {
    url = "https://github.com/gbdk-2020/gbdk-2020/releases/download/${version}/gbdk-${os}.tar.gz";
    sha256 = "sPDOEwZXYJ4x9kR8108kJKje7vH/ziXnKlsMdB02w/s=";
  };

  doCheck = true;
  checkPhase = ''
      cd examples/gb
      make |& tee gdbc-nix-test.log >&2
      cd ../..
  '';

  installPhase = ''
    mkdir -p $out
    cp -r lib bin include $out
  '';

  meta = with lib; {
    description = "An updated version of GBDK, A C compiler, assembler, linker and set of libraries for the Z80 like Nintendo Gameboy. ";
    longDescription = ''
        GBDK is a cross-platform development kit for sm83 and z80 based gaming consoles. It includes libraries, toolchain utilities and the SDCC C compiler suite.
    '';
    homepage = "https://github.com/gbdk-2020/gbdk-2020";
    license = licenses.gpl2;
    platforms = platforms.all;
  };
}
```

When spinning up a shell with `gbdk` as a dependency, via the `shell.nix` file

```nix
{ pkgs ? import <nixpkgs> {} }:
let
  gbdk = (import ./default.nix) {
    inherit pkgs;
  };
in pkgs.mkShell {
  buildInputs = [
    gbdk
  ];
}
```

and after suitably editing the provided `Makefile`s, I get the following output when trying to build the examples.

```bash
[nix-shell:~/Documents/Projects/gbdk/gb/bcd]$ which lcc
/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/lcc
[nix-shell:~/Documents/Projects/gbdk/gb/bcd]$ which sdcc
/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/sdcc
lcc -Wa-l -Wl-m -Wl-j -o bcd.gb bcd.c
lcc: /opt/gbdk/bin/sdcc: No such file or directory
make: *** [Makefile:13: bcd.gb] Error 1
```

During the check phase all the examples in the `examples` directory build correctly.

I'm using the macos build - is the location of `sdcc` hardcoded to `/opt/gbdk/bin/sdcc`?

**Comment by bbbbbr** [comment]
What are the edits referred to by this: 
> and after suitably editing the provided Makefiles

Also, you may add `-v` to the `lcc` invocation to show the commands it tries to execute for building.

**Comment by AlexDalt** [comment]
I switched out the line
```
CC	= ../../../bin/lcc -Wa-l -Wl-m -Wl-j
```
for
```
CC  = lcc -Wa-l -Wl-m -Wl-j
```
so it uses the one installed by nixpkg at `/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/lcc`

adding the `-v` flag the output is now
```
[nix-shell:~/Documents/Projects/gbdk/gb/bcd]$ make
lcc -v -Wa-l -Wl-m -Wl-j -o bcd.gb bcd.c
lcc $Id: lcc.c,v 2.0 2022/11/05 04:00:31 gbdk-2020 Exp $
/opt/gbdk/bin/sdcc -msm83 --no-std-crt0 --fsigned-char --use-stdout -D__PORT_sm83 -D__TARGET_gb -Wa-pogn -I/opt/gbdk/lib/gb -DINT_16_BITS -I/opt/gbdk/include -c bcd.c -o /tmp/lcc623850.o
lcc: /opt/gbdk/bin/sdcc: No such file or directory
rm /tmp/lcc623850.adb /tmp/lcc623850.o /tmp/lcc623850.asm /tmp/lcc623850.lst /tmp/lcc623850.sym

make: *** [Makefile:13: bcd.gb] Error 1
```

**Comment by bbbbbr** [comment]
Thanks for the info.

- `lcc` tries to determine the GBDK install dir by examining the command used to invoke it (`argv[0]`) using `set_gbdk_dir()`.
-  This does not succeed on Linux (& likely macOS) when it's invoked via system path search instead of using an explicit path, so it reverts to the hard coded fallback path (`/opt/gbdk`)

The alternative is to use the `GBDKDIR` environment var to indicate where the GBDK base path is. For example: `export GBDKDIR=/home/someuser/gbdk/`

It looks like I recently broke the ` --sdccbindir=` override argument, so that option is not available in the current release. Unsure how many know about that and use it, as it isn't documented. I'll have to fix that.

Unsure if we'd want to change the behavior to resolve the executable process path if the explicit path is missing. There may be some usage which depends on the hard coded path as fallback behavior (see #13.) @basxto has more familiarity with that.

**Comment by AlexDalt** [comment]
Okay, that's good to know. Adding
```nix
  shellHook = ''
    export GBDKDIR=${gbdk}/
  '';
```
to the `shell.nix` file worked for finding `sdcc`. Although it would be good to find a more nix-like approach that only requires work in the `default.nix` file and then `shell.nix` can simply import this as a dependency.

I've now got the problem that it can't seem to locate the header files nested in subdirectories within the `include` directory.

```bash
[nix-shell:~/Documents/Projects/gbdk/gb/bcd]$ make
lcc -v -Wa-l -Wl-m -Wl-j -o bcd.gb bcd.c
lcc $Id: lcc.c,v 2.0 2022/11/05 04:00:31 gbdk-2020 Exp $
/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/sdcc -msm83 --no-std-crt0 --fsigned-char --use-stdout -D__PORT_sm83 -D__TARGET_gb -Wa-pogn -I/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/gb -DINT_16_BITS -I/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/include -c bcd.c -o /tmp/lcc21050.o
/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/sdldgb -n -i -m -j -g _shadow_OAM=0xC000 -g .STACK=0xE000 -g .refresh_OAM=0xFF80 -b _DATA=0xC0A0 -b _CODE=0x0200 -k /nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/sm83/ -l sm83.lib -k /nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/gb/ -l gb.lib bcd.ihx /nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/gb/crt0.o /tmp/lcc21050.o

?ASlink-Warning-Undefined Global '_font_set' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_bcd_add' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_font_spect' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_font_load' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_font_init' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_bcd_sub' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_uint2bcd' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_set_bkg_tiles' referenced by module 'bcd'

?ASlink-Warning-Undefined Global '_bcd2text' referenced by module 'bcd'
/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/ihxcheck bcd.ihx
rm /tmp/lcc21050.adb bcd.ihx /tmp/lcc21050.o /tmp/lcc21050.asm /tmp/lcc21050.lst /tmp/lcc21050.sym

make: *** [Makefile:14: bcd.gb] Error 1
```
I'm not sure if this is a fault with the nix config not properly linking to thinks or whatnot. How can I access more debug information?

**Comment by untoxa** [comment]
no, it simply can't find lib files on the linking stage.

**Comment by AlexDalt** [comment]
Is that strange? It looks like `sdldgb` is looking in the correct directories, `/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/sm83/` and such

**Comment by bbbbbr** [comment]
I'm not able to reproduce that when I try to generally reproduce your setup (path wise, at least). Are the pre-built libraries it is looking for correctly installed?

Also odd that the build date for your lcc version is off by 11 seconds from the official one. Are you using the pre-built 4.1.1 release package?
```
 export GBDKDIR=/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/

$ lcc -v -Wa-l -Wl-m -Wl-j -o bcd.gb bcd.c 
lcc $Id: lcc.c,v 2.0 2022/11/05 04:00:20 gbdk-2020 Exp $
/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/sdcc -msm83 --no-std-crt0 --fsigned-char --use-stdout -D__PORT_sm83 -D__TARGET_gb -Wa-pogn -I/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/gb -DINT_16_BITS -I/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/include -c bcd.c -o /tmp/lcc24421540.o

/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/sdldgb -n -i -m -j -g _shadow_OAM=0xC000 -g .STACK=0xE000 -g .refresh_OAM=0xFF80 -b _DATA=0xC0A0 -b _CODE=0x0200 -k /nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/sm83/ -l sm83.lib -k /nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/gb/ -l gb.lib bcd.ihx /nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/lib/gb/crt0.o /tmp/lcc24421540.o

/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/ihxcheck bcd.ihx

/nix/store/5ifkn1s3g050wkh4vx39j2xbjs7nh6d4-gbdk/bin/makebin -yN -Z bcd.ihx bcd.gb

rm /tmp/lcc24421540.adb bcd.ihx /tmp/lcc24421540.o /tmp/lcc24421540.asm /tmp/lcc24421540.lst /tmp/lcc24421540.sym
````

**Comment by AlexDalt** [comment]
I'm definitely using the pre-built 4.1.1, but I'm using the macos build so that might account for the 11 second discrepency. I'm sure I've installed the libraries correctly, but for peace of mind what steps should I be taking?

**Comment by AlexDalt** [comment]
On my local system everything works as expected when I'm not using nix to handle the gbdk installation, so I think it's now a problem with my understanding of Nix.
