### ISSUE TITLE
Test current sdcc (before 4.3.0 release)

### ISSUE THREAD

**Issue by spth** [gbdk-2020/gbdk-2020#474]
SDCC developers intend to do a 4.3.0 release soon. While the official release process with code freezes, etc hasn't been started yet, this seems like a good time to test if gbdk works well with SDCC from current svn, and report any found SDCC issues upstream, while there is still a chance to fix them before 4.3.0.

SDCC progress since 4.2.0 was mostly in improved standard compliance; a large number of bugs have been fixed, too.

**Comment by untoxa** [comment]
I am just testing the latest SDCC build. What i noticed already:
1. `sdar` tool refuses to make objects from `sdasgb` compiled assembly files, they look ok.
2. `-MMD` is now `-Wp-MMD`, but the .d files are not created beside the assembly objects but in the root folder of the project, beside the Makefile

**Comment by untoxa** [comment]
worse, old style `-MMF` option to sdcc result into:
```
gb/actor.o src/actor.c
sdcpp.exe: warning: '-x c' after last input file has no effect
cc1: fatal error: obj/gb/actor.d: No such file or directory
compilation terminated.
```
AND THAT TRUNCATES THE SOURCE *.C FILE TO THE ZERO SIZE!

**Comment by spth** [comment]
Thanks. Can you file SDCC bug reports (https://sourceforge.net/p/sdcc/bugs/) for these?

**Comment by bbbbbr** [comment]
Looks like there is an existing ticket for the -x c deletion bug here:
> #3541 SDCC deletes cpp file in compiling and throw an error
> https://sourceforge.net/p/sdcc/bugs/3541/

Thanks for reaching out to us btw, I'll try to do some testing too. 
Will build from source though since I'm on an LTS Linux with older GLIBC.

**Comment by bbbbbr** [comment]
Opened a forum topic with some build and packaging related questions here:
https://sourceforge.net/p/sdcc/discussion/1865/thread/83d2461277/

**Comment by bbbbbr** [comment]
A brief update on this- We've been testing for a few months with various sdcc builds (such as 13911,  more recently 14089). Now that we have the path and pre-processor issues resolved the new versions have been working well.

Thanks again for checking in with us.
