### ISSUE TITLE
Install on mac?

### ISSUE THREAD

**Issue by hoitomt1** [gbdk-2020/gbdk-2020#476]
I cant find out how to install the devkit on mac? the mac download link returns "nothing found" and i cant seem to download it through homebrew

**Comment by bbbbbr** [comment]
Thanks for reporting this, I've fixed the broken link from the landing page.

You can also download directly from the Releases page:
https://github.com/gbdk-2020/gbdk-2020/releases/

**Comment by untoxa** [comment]
https://github.com/gbdk-2020/gbdk-2020/releases/latest download the mac version, decompress and install manually. that is the only way for now.

**Comment by limitLiu** [comment]
I added a [gbdk homebrew formula](https://github.com/limitLiu/homebrew-formulae).
