### ISSUE TITLE
lcc unknown developer

### ISSUE THREAD

**Issue by hoitomt1** [gbdk-2020/gbdk-2020#477]
I get an unknown developer warning for lcc when trying to compile the examples, how come? Im new to this kind of programming

**Comment by bbbbbr** [comment]
We'll need to know a couple things:
* Version of GBDK-2020
* Operating System
* What command / environment you are using to build with, and what directory (a specific example? all examples?)
* What the error from LCC is, text or screenshot if it's a system popup

**Comment by hoitomt1** [comment]
<img width="377" alt="Screenshot 2023-02-12 at 00 12 29" src="https://user-images.githubusercontent.com/97731056/218285036-d12abbde-061b-45c1-a01d-15ce5e83e018.png">

**Comment by hoitomt1** [comment]
Sorry for closing, misunderstood. Im using the latest version of GBDK2020 from github on macos ventura 13.1, and i get these popups, first it was for lcc and now for png2asset. is there a way to get these developer verified?

**Comment by bbbbbr** [comment]
We currently don't have plans to obtain the ability to sign from Apple.

I will ask around to see what other users do to run it (as there are ~200 downloads of the current release for macOS).

Are you on an M1/M2 or an intel mac?

**Comment by bbbbbr** [comment]
A user has suggested:
> go into the folder where all of the gbdk binary files are, and do a right-click -> open on them. Once you’ve opened them once that way, they work just fine after that.

**Comment by hoitomt1** [comment]
> Are you on an M1/M2 or an intel mac?

im on an m1 Pro mac



> go into the folder where all of the gbdk binary files are, and do a right-click -> open on them. Once you’ve opened them once that way, they work just fine after that.

Will try this and see if it works

**Comment by bbbbbr** [comment]
Another user says:
> ... on my m1 mac. run make in the examples folder and have settings - security and privacy open, each time it stops, press Allow Anyway. After that everything worked fine.

![discord_IMG_5093](https://user-images.githubusercontent.com/8322401/218302169-0393f65c-295b-49bb-8548-a590583a8c76.jpeg)

**Comment by ukd1** [comment]
This is fixed with instructions added to the readme in #484

**Comment by bbbbbr** [comment]
Thanks again for following up on this and submitting a PR to document the workaround :+1:
