### ISSUE TITLE
Unable To Compile

### ISSUE THREAD

**Issue by sbloom85** [gbdk-2020/gbdk-2020#487]
I'm having difficulties compiling my ROM file, when I run my make batch file, I get the following errors:

?ASlink-Warning-Undefined Global '_main' referenced by module 'Runtime'

?ASlink-Warning-Undefined Global '_main' referenced by module 'font.ms'

?ASlink-Warning-Undefined Global '_main' referenced by module ''

?ASlink-Warning-Undefined Global '_main' referenced by module ''

?ASlink-Warning-Undefined Global '_main' referenced by module ''

?ASlink-Warning-Undefined Global '_main' referenced by module ''

?ASlink-Warning-Undefined Global '_main' referenced by module ''

Here's the code, it's a simple Hello World from Gaming Monsters' GBDK tutorial
```
#include "gbdk\include\gb\gb.h"
#include <stdio.h>

void Main()
{
    printf("Hello World");
}
```

**Comment by bbbbbr** [comment]
Please see the example projects as a way to get started. They should build without issue. If you need something simple then you can see the "Template" ones in the "gb" example folder.

Also recommend reading the section below of the documentation. Many of the Gaming Monsters tutorials are designed for GBDK before GBDK-2020. 
`Migrating From Pre-GBDK-2020 Tutorials`
https://gbdk-2020.github.io/gbdk-2020/docs/api/docs_getting_started.html#autotoc_md23

**Comment by sbloom85** [comment]
Okay. Kinda surprising because I was able to compile his stuff without problems last year. Thanks!

**Comment by bbbbbr** [comment]
I recommend following the Getting Started guide in the documentation and making sure the examples build.
