### ISSUE TITLE
how to install in visual studio 2022

### ISSUE THREAD

**Issue by retroarch-girl** [gbdk-2020/gbdk-2020#493]
Hi

how to install in visual studio 2022 please?

I don't know anything about make files.

**Comment by untoxa** [comment]
Use batch files as shown in `gbdk-2020/examples/gb/`. I am closing this issue because it is not a GBDK-2020 problem.

**Comment by retroarch-girl** [comment]
Is there a way to integrate gbdk into visual studio? Or can it be only compiled with batch files, manually?

Other C libraries I have used can be compiled in visual studio to produce the executable

**Comment by retroarch-girl** [comment]
ANSWER MOITHERFUCKER
