### ISSUE TITLE
Cannot be opened because developer cannot be verified. How to start?

### ISSUE THREAD

**Issue by DunhamGitHub** [gbdk-2020/gbdk-2020#551]
Downloaded "gbdk-macos.tar.gz".

Getting MacOS error below:

<img width="262" alt="Screenshot 2023-07-23 at 08 44 55" src="https://github.com/gbdk-2020/gbdk-2020/assets/6884752/bce7063a-711e-414a-81aa-71ab0fd4e901">

**Comment by bbbbbr** [comment]
See the solution in this issue:
https://github.com/gbdk-2020/gbdk-2020/issues/477#issuecomment-1451181059

**Comment by DunhamGitHub** [comment]
Thank you!
