### ISSUE TITLE
set_bkg_based_tiles() bug when w > 4

### ISSUE THREAD

**Issue by RodrigoCard** [gbdk-2020/gbdk-2020#584]
When I use something like this to set some tiles:
`set_bkg_based_tiles(posx,posy,8,1,hud_tiles, tile_base);`
just the first 4 tiles are correctly copied, anything after that shows undefined tile (generally FF tile)
this workaround did the job, but shouldnt be necessary:
```
if(how_many_tiles>4) {
    set_bkg_based_tiles(posx,posy,4,1,hud_tiles, tile_base);
    set_bkg_based_tiles(posx+4,posy,how_many_tiles-4,1,hud_tiles, tile_base);
} else {
    set_bkg_based_tiles(posx,posy,how_many_tiles,1,hud_tiles, tile_base);
}
```

thanks

**Comment by untoxa** [comment]
can't trigger the bug, everything is working as expected without any problems. please attach the minimal project that shows that behavior, otherwise i will close the issue. thank you.

**Comment by bbbbbr** [comment]
Closed for lack of activity
