### ISSUE TITLE
[REQUEST]Add CPU options for Commander X16 - Add 65c816 and 65ce02 support to LCC.

### ISSUE THREAD

**Issue by TheRealHamtaro126** [gbdk-2020/gbdk-2020#701]
I would like to request support for both CPU format options used in The 8-Bit Guy's Homebrew Dream Computer, the CX16, as I wish for a better C compiler than the other alternative... Does not support alternate 65-family CPUs (65c02 is an exception) and is not optimized well... (referencing CC65 here!)

I am hoping to reprogram a game that uses the same compiler, while maybe updating code... The original used Gameboy ASM along with the C code, but I do understand, because ASM is fun to translate, even if it is hard the logic is there...

All I need is this C compiler, and... both the CX16's CPU options, to fit the bill.

Then there is the VERA chip problem... It is still being worked on by the CX16 team... There can also be an option for the user to implement a simple set of variables/macros/etc. for VERA manually in a text editor? (based off the usual CX16 Firmware and ROM updates)

**Comment by bbbbbr** [comment]
This request seems like it may be better suited for the SDCC compiler team.
https://sourceforge.net/p/sdcc/feature-requests/

GBDK uses the compiler, and patches it some, but we are not it's maintainers.

**Comment by untoxa** [comment]
unlikely we can do anything before SDCC main branch receive support, even if we really want, we prefer not create such deep forks.
