### ISSUE TITLE
"move_metasprite_flipx" only flips once

### ISSUE THREAD

**Issue by Lazarus404** [gbdk-2020/gbdk-2020#704]
Hi guys,

I need my sprite to flip with every move.  I'm mimicking an old Game & Watch game and the sprite is moved tile-by-tile. However, when calling `move_metasprite_flipx`, the sprite flips the first time, then remains flipped with every subsequent call. It doesn't flip back.

Please advise.

Many thanks 🙏

**Comment by untoxa** [comment]
That is how this function is intended to work. if you need to flip the sprite every other frame, call move_metasprite() and move_metasprite_flipx() in turns. Issues is not a proper place to learn gbdk-2020, you can join to the gbdk-2020 discord for the community support, or use some retro development forum. Links may be found on the front page.

**Comment by Lazarus404** [comment]
There's a Discord?  Didn't know that.

Thanks, that fixed my issue.  All good.
