### ISSUE TITLE
Compiled NES ROMS open with Nestopia but not FCEU

### ISSUE THREAD

**Issue by hbons** [gbdk-2020/gbdk-2020#730]
When opening with FCEU only a grey background is displayed. They work fine with Nestopia. This is the cross platform Pong example:
<img width="439" alt="image" src="https://github.com/user-attachments/assets/a716ad5f-755e-4c46-8522-1594d98f1014">

**Comment by bbbbbr** [comment]
I don't know NES emulators well, but isn't FCEU rather old and maybe has more limited mapper support? The examples work ok in the updated and fairly current fork FCEUX. @michel-iwaniec knows this topic better than I do.

**Comment by michel-iwaniec** [comment]
FCEU is ancient and not expected to work.

We recommend Mesen: https://github.com/SourMesen/Mesen2?tab=readme-ov-file#development-builds
