### ISSUE TITLE
Asking for clarification on hblank_copy_vram behavior

### ISSUE THREAD

**Issue by zlash** [gbdk-2020/gbdk-2020#731]
I'm looking at the implementation of [hblank_copy_vram](https://github.com/gbdk-2020/gbdk-2020/blob/021069becba6477324f176af0856aafa326116e1/gbdk-lib/libc/targets/sm83/hblankcpy.s#L8) and I think there might be an issue with it.

Because IF is not reset, in the case there is a MODE_0 LCD_STAT interrupt issued between the moment interrupts are disabled and the first `halt` in `hblank_cpy_vram` is called, then the halt bug will happen and incorrect behavior introduced. If `hblank_copy_vram` is a "hands-off" alternative to `hblank_cpy_vram` I think this should be taken into account.

I stated it as a fact, but I'm not sure about it as I'm not that experienced. That's why I'm asking for clarification if a corrective action would be needed. I think I was affected by it and after some head scratching I think I fixed it by running it from a LYC=0 interrupt so I can be sure STAT was already cleared when called.

**Comment by zlash** [comment]
Of course, Thanks for the quick reply! I wonder what was causing my issue then. Will look at it better if it happens again.

**Comment by untoxa** [comment]
probably you have slow LCD ISR function and were unlucky at the same time, so mode 0 interrupt fired between the `ldh (rIF), a` and `halt`

**Comment by untoxa** [comment]
try this fix: https://github.com/gbdk-2020/gbdk-2020/commit/64cd76351bf32cac758c8aa39c74ceba92265347 download the gbdk-2020 build from the CI when it is ready

**Comment by zlash** [comment]
Thanks! That fixes it. For the record I have an incredibly slow ISR. It was just a quick test trying to see how much I can push during hblank in a loop. Thanks a lot!!
